version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pc_db
    ports:
      - "3308:3306"
    networks:
      - springboot-mysql-network

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-container
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/pc_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - springboot-mysql-network

networks:
  springboot-mysql-network:
    driver: bridge